version: '3.8'

services:
  postgres:
    container_name: famdesc-db
    image: postgres:16.2
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: docker-famdesc-db